### ISSUE TITLE
TT from DOP & Pin Ø - Error

### ISSUE THREAD

**Issue by JB-1956** [Precision-Technologies-Ltd/master-gauge-issues#11] opened 2023-10-13 10:24 UTC
Hi

TT coming back as -171.0873

DOS Program calculated: 4.8034

![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/146351525/a07a3165-c519-4040-a9a5-a3c7797821ed)

**Comment by inyoka** [comment] 2023-10-13 11:11
Thank you, I'll take a look.

**Comment by inyoka** [comment] 2023-10-13 13:20
This is caused by the DOP and Pin Dia being the wrong way round.  I have added an error message to help future users. 

From a usability perspective, would it feel more comfortable entering DOP before pin size?

![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/6580673/a470effb-b9c0-4c63-98e2-5cce382943b6)


![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/6580673/ddcfe8a6-ccb0-4204-9d06-41d3cd75340b)

![image](https://github.com/Precision-Technologies-Ltd/master-gauge-issues/assets/6580673/cf9b0610-3eea-4105-8b62-d1f50a280bb7)

**Comment by JB-1956** [comment] 2023-10-17 07:09
Hi Simon,

Sorry my fault.
I've asked in the office and its feels more natural to them to input the Pin Ø first and as you show it follows the old program.
So I would keep as is, and I'll pay more attention, the error message should solve.

Thanks
Jamie

**Comment by inyoka** [comment] 2023-10-17 16:00
Great, thank you.  I'll close the issue.  The next version will have the error check, and also allow entering DP instead of the module.

**Closed as completed by inyoka** 2023-10-17 16:00 UTC
